# Security Config

security:
  ocsp:
    cache:
      ttl: "1h"
  crl:
    ttl: "1h"
  certificates:
    tls_version: "TLS13"
    ca_cert_path: "./certs/ca.pem"
    server_cert_path: "./certs/server.pem"
    server_key_path: "./certs/server.key"
    client_cert_path: "./certs/client.pem"
    client_key_path: "./certs/client.key"
    retry_policy:
      max_retries: 3
      backoff: "15s"
      jitter: "5s"
  http_client:
    timeout: "10s"
    tls_version: "TLS13"
    max_idle_connections_per_host: 10
